/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as containerRouteRouteImport } from './routes/(container)/route'
import { Route as AtChar123nicknameChar125RouteRouteImport } from './routes/@{$nickname}/route'
import { Route as containerIndexRouteImport } from './routes/(container)/index'
import { Route as containerActivityRouteImport } from './routes/(container)/activity'
import { Route as containerLoginRouteImport } from './routes/(container)/login'
import { Route as containerMarketRouteImport } from './routes/(container)/market'
import { Route as containerTermsPrivacyRouteImport } from './routes/(container)/terms-privacy'
import { Route as AtChar123nicknameChar125IndexRouteImport } from './routes/@{$nickname}/index'
import { Route as AtChar123nicknameChar125ListRouteImport } from './routes/@{$nickname}/list'
import { Route as ApiCollectionRouteImport } from './routes/api/collection'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as ApiLiveSessionsRouteImport } from './routes/api/live-sessions'
import { Route as ApiOpenAppRouteImport } from './routes/api/open-app'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as containerAuthResetPasswordRouteImport } from './routes/(container)/auth/reset-password'
import { Route as containerAuthVerifiedRouteImport } from './routes/(container)/auth/verified'
import { Route as containerLinkIndexRouteImport } from './routes/(container)/link/index'
import { Route as containerLinkConnectRouteImport } from './routes/(container)/link/connect'
import { Route as containerListIndexRouteImport } from './routes/(container)/list/index'
import { Route as containerListSlugRouteImport } from './routes/(container)/list/$slug'
import { Route as containerLiveIndexRouteImport } from './routes/(container)/live/index'
import { Route as containerLiveIdRouteImport } from './routes/(container)/live/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiUserSearchRouteImport } from './routes/api/user.search'
import { Route as containerAtChar123nicknameChar125ListSlugRouteImport } from './routes/(container)/@{$nickname}_/list.$slug'
import { Route as ApiObjektsListCollectionSlugRouteImport } from './routes/api/objekts/list.$collectionSlug'
import { Route as ApiObjektsMetadataCollectionSlugRouteImport } from './routes/api/objekts/metadata.$collectionSlug'
import { Route as ApiObjektsTransfersCollectionSlugSerialRouteImport } from './routes/api/objekts/transfers.$collectionSlug.$serial'

const containerRouteRoute = containerRouteRouteImport.update({
  id: '/(container)',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123nicknameChar125RouteRoute =
  AtChar123nicknameChar125RouteRouteImport.update({
    id: '/@{$nickname}',
    path: '/@{$nickname}',
    getParentRoute: () => rootRouteImport,
  } as any)
const containerIndexRoute = containerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerActivityRoute = containerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerLoginRoute = containerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerMarketRoute = containerMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerTermsPrivacyRoute = containerTermsPrivacyRouteImport.update({
  id: '/terms-privacy',
  path: '/terms-privacy',
  getParentRoute: () => containerRouteRoute,
} as any)
const AtChar123nicknameChar125IndexRoute =
  AtChar123nicknameChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const AtChar123nicknameChar125ListRoute =
  AtChar123nicknameChar125ListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const ApiCollectionRoute = ApiCollectionRouteImport.update({
  id: '/api/collection',
  path: '/api/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSessionsRoute = ApiLiveSessionsRouteImport.update({
  id: '/api/live-sessions',
  path: '/api/live-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenAppRoute = ApiOpenAppRouteImport.update({
  id: '/api/open-app',
  path: '/api/open-app',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const containerAuthResetPasswordRoute =
  containerAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => containerRouteRoute,
  } as any)
const containerAuthVerifiedRoute = containerAuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerLinkIndexRoute = containerLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerLinkConnectRoute = containerLinkConnectRouteImport.update({
  id: '/link/connect',
  path: '/link/connect',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerListIndexRoute = containerListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerListSlugRoute = containerListSlugRouteImport.update({
  id: '/list/$slug',
  path: '/list/$slug',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerLiveIndexRoute = containerLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => containerRouteRoute,
} as any)
const containerLiveIdRoute = containerLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => containerRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSearchRoute = ApiUserSearchRouteImport.update({
  id: '/api/user/search',
  path: '/api/user/search',
  getParentRoute: () => rootRouteImport,
} as any)
const containerAtChar123nicknameChar125ListSlugRoute =
  containerAtChar123nicknameChar125ListSlugRouteImport.update({
    id: '/@{$nickname}_/list/$slug',
    path: '/@{$nickname}/list/$slug',
    getParentRoute: () => containerRouteRoute,
  } as any)
const ApiObjektsListCollectionSlugRoute =
  ApiObjektsListCollectionSlugRouteImport.update({
    id: '/api/objekts/list/$collectionSlug',
    path: '/api/objekts/list/$collectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObjektsMetadataCollectionSlugRoute =
  ApiObjektsMetadataCollectionSlugRouteImport.update({
    id: '/api/objekts/metadata/$collectionSlug',
    path: '/api/objekts/metadata/$collectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObjektsTransfersCollectionSlugSerialRoute =
  ApiObjektsTransfersCollectionSlugSerialRouteImport.update({
    id: '/api/objekts/transfers/$collectionSlug/$serial',
    path: '/api/objekts/transfers/$collectionSlug/$serial',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/@{$nickname}': typeof AtChar123nicknameChar125RouteRouteWithChildren
  '/activity': typeof containerActivityRoute
  '/login': typeof containerLoginRoute
  '/market': typeof containerMarketRoute
  '/terms-privacy': typeof containerTermsPrivacyRoute
  '/@{$nickname}/list': typeof AtChar123nicknameChar125ListRoute
  '/api/collection': typeof ApiCollectionRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/live-sessions': typeof ApiLiveSessionsRoute
  '/api/open-app': typeof ApiOpenAppRoute
  '/rpc/$': typeof RpcSplatRoute
  '/': typeof containerIndexRoute
  '/@{$nickname}/': typeof AtChar123nicknameChar125IndexRoute
  '/auth/reset-password': typeof containerAuthResetPasswordRoute
  '/auth/verified': typeof containerAuthVerifiedRoute
  '/link/connect': typeof containerLinkConnectRoute
  '/list/$slug': typeof containerListSlugRoute
  '/live/$id': typeof containerLiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/search': typeof ApiUserSearchRoute
  '/link/': typeof containerLinkIndexRoute
  '/list/': typeof containerListIndexRoute
  '/live/': typeof containerLiveIndexRoute
  '/@{$nickname}/list/$slug': typeof containerAtChar123nicknameChar125ListSlugRoute
  '/api/objekts/list/$collectionSlug': typeof ApiObjektsListCollectionSlugRoute
  '/api/objekts/metadata/$collectionSlug': typeof ApiObjektsMetadataCollectionSlugRoute
  '/api/objekts/transfers/$collectionSlug/$serial': typeof ApiObjektsTransfersCollectionSlugSerialRoute
}
export interface FileRoutesByTo {
  '/activity': typeof containerActivityRoute
  '/login': typeof containerLoginRoute
  '/market': typeof containerMarketRoute
  '/terms-privacy': typeof containerTermsPrivacyRoute
  '/@{$nickname}/list': typeof AtChar123nicknameChar125ListRoute
  '/api/collection': typeof ApiCollectionRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/live-sessions': typeof ApiLiveSessionsRoute
  '/api/open-app': typeof ApiOpenAppRoute
  '/rpc/$': typeof RpcSplatRoute
  '/': typeof containerIndexRoute
  '/@{$nickname}': typeof AtChar123nicknameChar125IndexRoute
  '/auth/reset-password': typeof containerAuthResetPasswordRoute
  '/auth/verified': typeof containerAuthVerifiedRoute
  '/link/connect': typeof containerLinkConnectRoute
  '/list/$slug': typeof containerListSlugRoute
  '/live/$id': typeof containerLiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/search': typeof ApiUserSearchRoute
  '/link': typeof containerLinkIndexRoute
  '/list': typeof containerListIndexRoute
  '/live': typeof containerLiveIndexRoute
  '/@{$nickname}/list/$slug': typeof containerAtChar123nicknameChar125ListSlugRoute
  '/api/objekts/list/$collectionSlug': typeof ApiObjektsListCollectionSlugRoute
  '/api/objekts/metadata/$collectionSlug': typeof ApiObjektsMetadataCollectionSlugRoute
  '/api/objekts/transfers/$collectionSlug/$serial': typeof ApiObjektsTransfersCollectionSlugSerialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(container)': typeof containerRouteRouteWithChildren
  '/@{$nickname}': typeof AtChar123nicknameChar125RouteRouteWithChildren
  '/(container)/activity': typeof containerActivityRoute
  '/(container)/login': typeof containerLoginRoute
  '/(container)/market': typeof containerMarketRoute
  '/(container)/terms-privacy': typeof containerTermsPrivacyRoute
  '/@{$nickname}/list': typeof AtChar123nicknameChar125ListRoute
  '/api/collection': typeof ApiCollectionRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/live-sessions': typeof ApiLiveSessionsRoute
  '/api/open-app': typeof ApiOpenAppRoute
  '/rpc/$': typeof RpcSplatRoute
  '/(container)/': typeof containerIndexRoute
  '/@{$nickname}/': typeof AtChar123nicknameChar125IndexRoute
  '/(container)/auth/reset-password': typeof containerAuthResetPasswordRoute
  '/(container)/auth/verified': typeof containerAuthVerifiedRoute
  '/(container)/link/connect': typeof containerLinkConnectRoute
  '/(container)/list/$slug': typeof containerListSlugRoute
  '/(container)/live/$id': typeof containerLiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/search': typeof ApiUserSearchRoute
  '/(container)/link/': typeof containerLinkIndexRoute
  '/(container)/list/': typeof containerListIndexRoute
  '/(container)/live/': typeof containerLiveIndexRoute
  '/(container)/@{$nickname}_/list/$slug': typeof containerAtChar123nicknameChar125ListSlugRoute
  '/api/objekts/list/$collectionSlug': typeof ApiObjektsListCollectionSlugRoute
  '/api/objekts/metadata/$collectionSlug': typeof ApiObjektsMetadataCollectionSlugRoute
  '/api/objekts/transfers/$collectionSlug/$serial': typeof ApiObjektsTransfersCollectionSlugSerialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/@{$nickname}'
    | '/activity'
    | '/login'
    | '/market'
    | '/terms-privacy'
    | '/@{$nickname}/list'
    | '/api/collection'
    | '/api/healthcheck'
    | '/api/live-sessions'
    | '/api/open-app'
    | '/rpc/$'
    | '/'
    | '/@{$nickname}/'
    | '/auth/reset-password'
    | '/auth/verified'
    | '/link/connect'
    | '/list/$slug'
    | '/live/$id'
    | '/api/auth/$'
    | '/api/user/search'
    | '/link/'
    | '/list/'
    | '/live/'
    | '/@{$nickname}/list/$slug'
    | '/api/objekts/list/$collectionSlug'
    | '/api/objekts/metadata/$collectionSlug'
    | '/api/objekts/transfers/$collectionSlug/$serial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/login'
    | '/market'
    | '/terms-privacy'
    | '/@{$nickname}/list'
    | '/api/collection'
    | '/api/healthcheck'
    | '/api/live-sessions'
    | '/api/open-app'
    | '/rpc/$'
    | '/'
    | '/@{$nickname}'
    | '/auth/reset-password'
    | '/auth/verified'
    | '/link/connect'
    | '/list/$slug'
    | '/live/$id'
    | '/api/auth/$'
    | '/api/user/search'
    | '/link'
    | '/list'
    | '/live'
    | '/@{$nickname}/list/$slug'
    | '/api/objekts/list/$collectionSlug'
    | '/api/objekts/metadata/$collectionSlug'
    | '/api/objekts/transfers/$collectionSlug/$serial'
  id:
    | '__root__'
    | '/(container)'
    | '/@{$nickname}'
    | '/(container)/activity'
    | '/(container)/login'
    | '/(container)/market'
    | '/(container)/terms-privacy'
    | '/@{$nickname}/list'
    | '/api/collection'
    | '/api/healthcheck'
    | '/api/live-sessions'
    | '/api/open-app'
    | '/rpc/$'
    | '/(container)/'
    | '/@{$nickname}/'
    | '/(container)/auth/reset-password'
    | '/(container)/auth/verified'
    | '/(container)/link/connect'
    | '/(container)/list/$slug'
    | '/(container)/live/$id'
    | '/api/auth/$'
    | '/api/user/search'
    | '/(container)/link/'
    | '/(container)/list/'
    | '/(container)/live/'
    | '/(container)/@{$nickname}_/list/$slug'
    | '/api/objekts/list/$collectionSlug'
    | '/api/objekts/metadata/$collectionSlug'
    | '/api/objekts/transfers/$collectionSlug/$serial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  containerRouteRoute: typeof containerRouteRouteWithChildren
  AtChar123nicknameChar125RouteRoute: typeof AtChar123nicknameChar125RouteRouteWithChildren
  ApiCollectionRoute: typeof ApiCollectionRoute
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiLiveSessionsRoute: typeof ApiLiveSessionsRoute
  ApiOpenAppRoute: typeof ApiOpenAppRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserSearchRoute: typeof ApiUserSearchRoute
  ApiObjektsListCollectionSlugRoute: typeof ApiObjektsListCollectionSlugRoute
  ApiObjektsMetadataCollectionSlugRoute: typeof ApiObjektsMetadataCollectionSlugRoute
  ApiObjektsTransfersCollectionSlugSerialRoute: typeof ApiObjektsTransfersCollectionSlugSerialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(container)': {
      id: '/(container)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof containerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$nickname}': {
      id: '/@{$nickname}'
      path: '/@{$nickname}'
      fullPath: '/@{$nickname}'
      preLoaderRoute: typeof AtChar123nicknameChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(container)/': {
      id: '/(container)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof containerIndexRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/activity': {
      id: '/(container)/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof containerActivityRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/login': {
      id: '/(container)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof containerLoginRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/market': {
      id: '/(container)/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof containerMarketRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/terms-privacy': {
      id: '/(container)/terms-privacy'
      path: '/terms-privacy'
      fullPath: '/terms-privacy'
      preLoaderRoute: typeof containerTermsPrivacyRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/@{$nickname}/': {
      id: '/@{$nickname}/'
      path: '/'
      fullPath: '/@{$nickname}/'
      preLoaderRoute: typeof AtChar123nicknameChar125IndexRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/@{$nickname}/list': {
      id: '/@{$nickname}/list'
      path: '/list'
      fullPath: '/@{$nickname}/list'
      preLoaderRoute: typeof AtChar123nicknameChar125ListRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/api/collection': {
      id: '/api/collection'
      path: '/api/collection'
      fullPath: '/api/collection'
      preLoaderRoute: typeof ApiCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-sessions': {
      id: '/api/live-sessions'
      path: '/api/live-sessions'
      fullPath: '/api/live-sessions'
      preLoaderRoute: typeof ApiLiveSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/open-app': {
      id: '/api/open-app'
      path: '/api/open-app'
      fullPath: '/api/open-app'
      preLoaderRoute: typeof ApiOpenAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(container)/auth/reset-password': {
      id: '/(container)/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof containerAuthResetPasswordRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/auth/verified': {
      id: '/(container)/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof containerAuthVerifiedRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/link/': {
      id: '/(container)/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof containerLinkIndexRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/link/connect': {
      id: '/(container)/link/connect'
      path: '/link/connect'
      fullPath: '/link/connect'
      preLoaderRoute: typeof containerLinkConnectRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/list/': {
      id: '/(container)/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof containerListIndexRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/list/$slug': {
      id: '/(container)/list/$slug'
      path: '/list/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof containerListSlugRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/live/': {
      id: '/(container)/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof containerLiveIndexRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/(container)/live/$id': {
      id: '/(container)/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof containerLiveIdRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/search': {
      id: '/api/user/search'
      path: '/api/user/search'
      fullPath: '/api/user/search'
      preLoaderRoute: typeof ApiUserSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(container)/@{$nickname}_/list/$slug': {
      id: '/(container)/@{$nickname}_/list/$slug'
      path: '/@{$nickname}/list/$slug'
      fullPath: '/@{$nickname}/list/$slug'
      preLoaderRoute: typeof containerAtChar123nicknameChar125ListSlugRouteImport
      parentRoute: typeof containerRouteRoute
    }
    '/api/objekts/list/$collectionSlug': {
      id: '/api/objekts/list/$collectionSlug'
      path: '/api/objekts/list/$collectionSlug'
      fullPath: '/api/objekts/list/$collectionSlug'
      preLoaderRoute: typeof ApiObjektsListCollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objekts/metadata/$collectionSlug': {
      id: '/api/objekts/metadata/$collectionSlug'
      path: '/api/objekts/metadata/$collectionSlug'
      fullPath: '/api/objekts/metadata/$collectionSlug'
      preLoaderRoute: typeof ApiObjektsMetadataCollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objekts/transfers/$collectionSlug/$serial': {
      id: '/api/objekts/transfers/$collectionSlug/$serial'
      path: '/api/objekts/transfers/$collectionSlug/$serial'
      fullPath: '/api/objekts/transfers/$collectionSlug/$serial'
      preLoaderRoute: typeof ApiObjektsTransfersCollectionSlugSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface containerRouteRouteChildren {
  containerActivityRoute: typeof containerActivityRoute
  containerLoginRoute: typeof containerLoginRoute
  containerMarketRoute: typeof containerMarketRoute
  containerTermsPrivacyRoute: typeof containerTermsPrivacyRoute
  containerIndexRoute: typeof containerIndexRoute
  containerAuthResetPasswordRoute: typeof containerAuthResetPasswordRoute
  containerAuthVerifiedRoute: typeof containerAuthVerifiedRoute
  containerLinkConnectRoute: typeof containerLinkConnectRoute
  containerListSlugRoute: typeof containerListSlugRoute
  containerLiveIdRoute: typeof containerLiveIdRoute
  containerLinkIndexRoute: typeof containerLinkIndexRoute
  containerListIndexRoute: typeof containerListIndexRoute
  containerLiveIndexRoute: typeof containerLiveIndexRoute
  containerAtChar123nicknameChar125ListSlugRoute: typeof containerAtChar123nicknameChar125ListSlugRoute
}

const containerRouteRouteChildren: containerRouteRouteChildren = {
  containerActivityRoute: containerActivityRoute,
  containerLoginRoute: containerLoginRoute,
  containerMarketRoute: containerMarketRoute,
  containerTermsPrivacyRoute: containerTermsPrivacyRoute,
  containerIndexRoute: containerIndexRoute,
  containerAuthResetPasswordRoute: containerAuthResetPasswordRoute,
  containerAuthVerifiedRoute: containerAuthVerifiedRoute,
  containerLinkConnectRoute: containerLinkConnectRoute,
  containerListSlugRoute: containerListSlugRoute,
  containerLiveIdRoute: containerLiveIdRoute,
  containerLinkIndexRoute: containerLinkIndexRoute,
  containerListIndexRoute: containerListIndexRoute,
  containerLiveIndexRoute: containerLiveIndexRoute,
  containerAtChar123nicknameChar125ListSlugRoute:
    containerAtChar123nicknameChar125ListSlugRoute,
}

const containerRouteRouteWithChildren = containerRouteRoute._addFileChildren(
  containerRouteRouteChildren,
)

interface AtChar123nicknameChar125RouteRouteChildren {
  AtChar123nicknameChar125ListRoute: typeof AtChar123nicknameChar125ListRoute
  AtChar123nicknameChar125IndexRoute: typeof AtChar123nicknameChar125IndexRoute
}

const AtChar123nicknameChar125RouteRouteChildren: AtChar123nicknameChar125RouteRouteChildren =
  {
    AtChar123nicknameChar125ListRoute: AtChar123nicknameChar125ListRoute,
    AtChar123nicknameChar125IndexRoute: AtChar123nicknameChar125IndexRoute,
  }

const AtChar123nicknameChar125RouteRouteWithChildren =
  AtChar123nicknameChar125RouteRoute._addFileChildren(
    AtChar123nicknameChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  containerRouteRoute: containerRouteRouteWithChildren,
  AtChar123nicknameChar125RouteRoute:
    AtChar123nicknameChar125RouteRouteWithChildren,
  ApiCollectionRoute: ApiCollectionRoute,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiLiveSessionsRoute: ApiLiveSessionsRoute,
  ApiOpenAppRoute: ApiOpenAppRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserSearchRoute: ApiUserSearchRoute,
  ApiObjektsListCollectionSlugRoute: ApiObjektsListCollectionSlugRoute,
  ApiObjektsMetadataCollectionSlugRoute: ApiObjektsMetadataCollectionSlugRoute,
  ApiObjektsTransfersCollectionSlugSerialRoute:
    ApiObjektsTransfersCollectionSlugSerialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
