/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContainerRouteImport } from './routes/_container'
import { Route as AtnicknameRouteImport } from './routes/@$nickname'
import { Route as ContainerIndexRouteImport } from './routes/_container/index'
import { Route as AtnicknameIndexRouteImport } from './routes/@$nickname/index'
import { Route as ContainerTermsPrivacyRouteImport } from './routes/_container/terms-privacy'
import { Route as ContainerLoginRouteImport } from './routes/_container/login'
import { Route as ContainerActivityRouteImport } from './routes/_container/activity'
import { Route as AtnicknameTradesRouteImport } from './routes/@$nickname/trades'
import { Route as AtnicknameStatsRouteImport } from './routes/@$nickname/stats'
import { Route as AtnicknameProgressRouteImport } from './routes/@$nickname/progress'
import { Route as AtnicknameListRouteImport } from './routes/@$nickname/list'
import { Route as ContainerLiveIndexRouteImport } from './routes/_container/live/index'
import { Route as ContainerListIndexRouteImport } from './routes/_container/list/index'
import { Route as ContainerLinkIndexRouteImport } from './routes/_container/link/index'
import { Route as ContainerLiveIdRouteImport } from './routes/_container/live/$id'
import { Route as ContainerListSlugRouteImport } from './routes/_container/list/$slug'
import { Route as ContainerLinkConnectRouteImport } from './routes/_container/link/connect'
import { Route as ContainerAuthVerifiedRouteImport } from './routes/_container/auth/verified'
import { Route as ContainerAuthResetPasswordRouteImport } from './routes/_container/auth/reset-password'
import { Route as AtnicknameListSlugRouteImport } from './routes/@$nickname/list.$slug'
import { Route as ContainerProfileListNicknameSlugRouteImport } from './routes/_container/profile-list/$nickname/$slug'

const ContainerRoute = ContainerRouteImport.update({
  id: '/_container',
  getParentRoute: () => rootRouteImport,
} as any)
const AtnicknameRoute = AtnicknameRouteImport.update({
  id: '/@$nickname',
  path: '/@$nickname',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerIndexRoute = ContainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainerRoute,
} as any)
const AtnicknameIndexRoute = AtnicknameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtnicknameRoute,
} as any)
const ContainerTermsPrivacyRoute = ContainerTermsPrivacyRouteImport.update({
  id: '/terms-privacy',
  path: '/terms-privacy',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLoginRoute = ContainerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerActivityRoute = ContainerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ContainerRoute,
} as any)
const AtnicknameTradesRoute = AtnicknameTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AtnicknameRoute,
} as any)
const AtnicknameStatsRoute = AtnicknameStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AtnicknameRoute,
} as any)
const AtnicknameProgressRoute = AtnicknameProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AtnicknameRoute,
} as any)
const AtnicknameListRoute = AtnicknameListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AtnicknameRoute,
} as any)
const ContainerLiveIndexRoute = ContainerLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerListIndexRoute = ContainerListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLinkIndexRoute = ContainerLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLiveIdRoute = ContainerLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerListSlugRoute = ContainerListSlugRouteImport.update({
  id: '/list/$slug',
  path: '/list/$slug',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLinkConnectRoute = ContainerLinkConnectRouteImport.update({
  id: '/link/connect',
  path: '/link/connect',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerAuthVerifiedRoute = ContainerAuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerAuthResetPasswordRoute =
  ContainerAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => ContainerRoute,
  } as any)
const AtnicknameListSlugRoute = AtnicknameListSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AtnicknameListRoute,
} as any)
const ContainerProfileListNicknameSlugRoute =
  ContainerProfileListNicknameSlugRouteImport.update({
    id: '/profile-list/$nickname/$slug',
    path: '/profile-list/$nickname/$slug',
    getParentRoute: () => ContainerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/@$nickname': typeof AtnicknameRouteWithChildren
  '/': typeof ContainerIndexRoute
  '/@$nickname/list': typeof AtnicknameListRouteWithChildren
  '/@$nickname/progress': typeof AtnicknameProgressRoute
  '/@$nickname/stats': typeof AtnicknameStatsRoute
  '/@$nickname/trades': typeof AtnicknameTradesRoute
  '/activity': typeof ContainerActivityRoute
  '/login': typeof ContainerLoginRoute
  '/terms-privacy': typeof ContainerTermsPrivacyRoute
  '/@$nickname/': typeof AtnicknameIndexRoute
  '/@$nickname/list/$slug': typeof AtnicknameListSlugRoute
  '/auth/reset-password': typeof ContainerAuthResetPasswordRoute
  '/auth/verified': typeof ContainerAuthVerifiedRoute
  '/link/connect': typeof ContainerLinkConnectRoute
  '/list/$slug': typeof ContainerListSlugRoute
  '/live/$id': typeof ContainerLiveIdRoute
  '/link/': typeof ContainerLinkIndexRoute
  '/list/': typeof ContainerListIndexRoute
  '/live/': typeof ContainerLiveIndexRoute
  '/profile-list/$nickname/$slug': typeof ContainerProfileListNicknameSlugRoute
}
export interface FileRoutesByTo {
  '/@$nickname/list': typeof AtnicknameListRouteWithChildren
  '/@$nickname/progress': typeof AtnicknameProgressRoute
  '/@$nickname/stats': typeof AtnicknameStatsRoute
  '/@$nickname/trades': typeof AtnicknameTradesRoute
  '/activity': typeof ContainerActivityRoute
  '/login': typeof ContainerLoginRoute
  '/terms-privacy': typeof ContainerTermsPrivacyRoute
  '/@$nickname': typeof AtnicknameIndexRoute
  '/': typeof ContainerIndexRoute
  '/@$nickname/list/$slug': typeof AtnicknameListSlugRoute
  '/auth/reset-password': typeof ContainerAuthResetPasswordRoute
  '/auth/verified': typeof ContainerAuthVerifiedRoute
  '/link/connect': typeof ContainerLinkConnectRoute
  '/list/$slug': typeof ContainerListSlugRoute
  '/live/$id': typeof ContainerLiveIdRoute
  '/link': typeof ContainerLinkIndexRoute
  '/list': typeof ContainerListIndexRoute
  '/live': typeof ContainerLiveIndexRoute
  '/profile-list/$nickname/$slug': typeof ContainerProfileListNicknameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/@$nickname': typeof AtnicknameRouteWithChildren
  '/_container': typeof ContainerRouteWithChildren
  '/@$nickname/list': typeof AtnicknameListRouteWithChildren
  '/@$nickname/progress': typeof AtnicknameProgressRoute
  '/@$nickname/stats': typeof AtnicknameStatsRoute
  '/@$nickname/trades': typeof AtnicknameTradesRoute
  '/_container/activity': typeof ContainerActivityRoute
  '/_container/login': typeof ContainerLoginRoute
  '/_container/terms-privacy': typeof ContainerTermsPrivacyRoute
  '/@$nickname/': typeof AtnicknameIndexRoute
  '/_container/': typeof ContainerIndexRoute
  '/@$nickname/list/$slug': typeof AtnicknameListSlugRoute
  '/_container/auth/reset-password': typeof ContainerAuthResetPasswordRoute
  '/_container/auth/verified': typeof ContainerAuthVerifiedRoute
  '/_container/link/connect': typeof ContainerLinkConnectRoute
  '/_container/list/$slug': typeof ContainerListSlugRoute
  '/_container/live/$id': typeof ContainerLiveIdRoute
  '/_container/link/': typeof ContainerLinkIndexRoute
  '/_container/list/': typeof ContainerListIndexRoute
  '/_container/live/': typeof ContainerLiveIndexRoute
  '/_container/profile-list/$nickname/$slug': typeof ContainerProfileListNicknameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/@$nickname'
    | '/'
    | '/@$nickname/list'
    | '/@$nickname/progress'
    | '/@$nickname/stats'
    | '/@$nickname/trades'
    | '/activity'
    | '/login'
    | '/terms-privacy'
    | '/@$nickname/'
    | '/@$nickname/list/$slug'
    | '/auth/reset-password'
    | '/auth/verified'
    | '/link/connect'
    | '/list/$slug'
    | '/live/$id'
    | '/link/'
    | '/list/'
    | '/live/'
    | '/profile-list/$nickname/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/@$nickname/list'
    | '/@$nickname/progress'
    | '/@$nickname/stats'
    | '/@$nickname/trades'
    | '/activity'
    | '/login'
    | '/terms-privacy'
    | '/@$nickname'
    | '/'
    | '/@$nickname/list/$slug'
    | '/auth/reset-password'
    | '/auth/verified'
    | '/link/connect'
    | '/list/$slug'
    | '/live/$id'
    | '/link'
    | '/list'
    | '/live'
    | '/profile-list/$nickname/$slug'
  id:
    | '__root__'
    | '/@$nickname'
    | '/_container'
    | '/@$nickname/list'
    | '/@$nickname/progress'
    | '/@$nickname/stats'
    | '/@$nickname/trades'
    | '/_container/activity'
    | '/_container/login'
    | '/_container/terms-privacy'
    | '/@$nickname/'
    | '/_container/'
    | '/@$nickname/list/$slug'
    | '/_container/auth/reset-password'
    | '/_container/auth/verified'
    | '/_container/link/connect'
    | '/_container/list/$slug'
    | '/_container/live/$id'
    | '/_container/link/'
    | '/_container/list/'
    | '/_container/live/'
    | '/_container/profile-list/$nickname/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AtnicknameRoute: typeof AtnicknameRouteWithChildren
  ContainerRoute: typeof ContainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_container': {
      id: '/_container'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ContainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$nickname': {
      id: '/@$nickname'
      path: '/@$nickname'
      fullPath: '/@$nickname'
      preLoaderRoute: typeof AtnicknameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_container/': {
      id: '/_container/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ContainerIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/@$nickname/': {
      id: '/@$nickname/'
      path: '/'
      fullPath: '/@$nickname/'
      preLoaderRoute: typeof AtnicknameIndexRouteImport
      parentRoute: typeof AtnicknameRoute
    }
    '/_container/terms-privacy': {
      id: '/_container/terms-privacy'
      path: '/terms-privacy'
      fullPath: '/terms-privacy'
      preLoaderRoute: typeof ContainerTermsPrivacyRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/login': {
      id: '/_container/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ContainerLoginRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/activity': {
      id: '/_container/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ContainerActivityRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/@$nickname/trades': {
      id: '/@$nickname/trades'
      path: '/trades'
      fullPath: '/@$nickname/trades'
      preLoaderRoute: typeof AtnicknameTradesRouteImport
      parentRoute: typeof AtnicknameRoute
    }
    '/@$nickname/stats': {
      id: '/@$nickname/stats'
      path: '/stats'
      fullPath: '/@$nickname/stats'
      preLoaderRoute: typeof AtnicknameStatsRouteImport
      parentRoute: typeof AtnicknameRoute
    }
    '/@$nickname/progress': {
      id: '/@$nickname/progress'
      path: '/progress'
      fullPath: '/@$nickname/progress'
      preLoaderRoute: typeof AtnicknameProgressRouteImport
      parentRoute: typeof AtnicknameRoute
    }
    '/@$nickname/list': {
      id: '/@$nickname/list'
      path: '/list'
      fullPath: '/@$nickname/list'
      preLoaderRoute: typeof AtnicknameListRouteImport
      parentRoute: typeof AtnicknameRoute
    }
    '/_container/live/': {
      id: '/_container/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof ContainerLiveIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/list/': {
      id: '/_container/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof ContainerListIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/link/': {
      id: '/_container/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof ContainerLinkIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/live/$id': {
      id: '/_container/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof ContainerLiveIdRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/list/$slug': {
      id: '/_container/list/$slug'
      path: '/list/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ContainerListSlugRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/link/connect': {
      id: '/_container/link/connect'
      path: '/link/connect'
      fullPath: '/link/connect'
      preLoaderRoute: typeof ContainerLinkConnectRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/auth/verified': {
      id: '/_container/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof ContainerAuthVerifiedRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/auth/reset-password': {
      id: '/_container/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof ContainerAuthResetPasswordRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/@$nickname/list/$slug': {
      id: '/@$nickname/list/$slug'
      path: '/$slug'
      fullPath: '/@$nickname/list/$slug'
      preLoaderRoute: typeof AtnicknameListSlugRouteImport
      parentRoute: typeof AtnicknameListRoute
    }
    '/_container/profile-list/$nickname/$slug': {
      id: '/_container/profile-list/$nickname/$slug'
      path: '/profile-list/$nickname/$slug'
      fullPath: '/profile-list/$nickname/$slug'
      preLoaderRoute: typeof ContainerProfileListNicknameSlugRouteImport
      parentRoute: typeof ContainerRoute
    }
  }
}

interface AtnicknameListRouteChildren {
  AtnicknameListSlugRoute: typeof AtnicknameListSlugRoute
}

const AtnicknameListRouteChildren: AtnicknameListRouteChildren = {
  AtnicknameListSlugRoute: AtnicknameListSlugRoute,
}

const AtnicknameListRouteWithChildren = AtnicknameListRoute._addFileChildren(
  AtnicknameListRouteChildren,
)

interface AtnicknameRouteChildren {
  AtnicknameListRoute: typeof AtnicknameListRouteWithChildren
  AtnicknameProgressRoute: typeof AtnicknameProgressRoute
  AtnicknameStatsRoute: typeof AtnicknameStatsRoute
  AtnicknameTradesRoute: typeof AtnicknameTradesRoute
  AtnicknameIndexRoute: typeof AtnicknameIndexRoute
}

const AtnicknameRouteChildren: AtnicknameRouteChildren = {
  AtnicknameListRoute: AtnicknameListRouteWithChildren,
  AtnicknameProgressRoute: AtnicknameProgressRoute,
  AtnicknameStatsRoute: AtnicknameStatsRoute,
  AtnicknameTradesRoute: AtnicknameTradesRoute,
  AtnicknameIndexRoute: AtnicknameIndexRoute,
}

const AtnicknameRouteWithChildren = AtnicknameRoute._addFileChildren(
  AtnicknameRouteChildren,
)

interface ContainerRouteChildren {
  ContainerActivityRoute: typeof ContainerActivityRoute
  ContainerLoginRoute: typeof ContainerLoginRoute
  ContainerTermsPrivacyRoute: typeof ContainerTermsPrivacyRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
  ContainerAuthResetPasswordRoute: typeof ContainerAuthResetPasswordRoute
  ContainerAuthVerifiedRoute: typeof ContainerAuthVerifiedRoute
  ContainerLinkConnectRoute: typeof ContainerLinkConnectRoute
  ContainerListSlugRoute: typeof ContainerListSlugRoute
  ContainerLiveIdRoute: typeof ContainerLiveIdRoute
  ContainerLinkIndexRoute: typeof ContainerLinkIndexRoute
  ContainerListIndexRoute: typeof ContainerListIndexRoute
  ContainerLiveIndexRoute: typeof ContainerLiveIndexRoute
  ContainerProfileListNicknameSlugRoute: typeof ContainerProfileListNicknameSlugRoute
}

const ContainerRouteChildren: ContainerRouteChildren = {
  ContainerActivityRoute: ContainerActivityRoute,
  ContainerLoginRoute: ContainerLoginRoute,
  ContainerTermsPrivacyRoute: ContainerTermsPrivacyRoute,
  ContainerIndexRoute: ContainerIndexRoute,
  ContainerAuthResetPasswordRoute: ContainerAuthResetPasswordRoute,
  ContainerAuthVerifiedRoute: ContainerAuthVerifiedRoute,
  ContainerLinkConnectRoute: ContainerLinkConnectRoute,
  ContainerListSlugRoute: ContainerListSlugRoute,
  ContainerLiveIdRoute: ContainerLiveIdRoute,
  ContainerLinkIndexRoute: ContainerLinkIndexRoute,
  ContainerListIndexRoute: ContainerListIndexRoute,
  ContainerLiveIndexRoute: ContainerLiveIndexRoute,
  ContainerProfileListNicknameSlugRoute: ContainerProfileListNicknameSlugRoute,
}

const ContainerRouteWithChildren = ContainerRoute._addFileChildren(
  ContainerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AtnicknameRoute: AtnicknameRouteWithChildren,
  ContainerRoute: ContainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
