/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContainerRouteImport } from './routes/_container'
import { Route as AtChar123nicknameChar125RouteRouteImport } from './routes/@{$nickname}/route'
import { Route as ContainerIndexRouteImport } from './routes/_container/index'
import { Route as AtChar123nicknameChar125IndexRouteImport } from './routes/@{$nickname}/index'
import { Route as RpcSplatRouteImport } from './routes/rpc.$'
import { Route as ApiOpenAppRouteImport } from './routes/api/open-app'
import { Route as ApiLiveSessionsRouteImport } from './routes/api/live-sessions'
import { Route as ApiHealthcheckRouteImport } from './routes/api/healthcheck'
import { Route as ApiCollectionRouteImport } from './routes/api/collection'
import { Route as ApiActivityRouteImport } from './routes/api/activity'
import { Route as ContainerTermsPrivacyRouteImport } from './routes/_container/terms-privacy'
import { Route as ContainerLoginRouteImport } from './routes/_container/login'
import { Route as ContainerCompareToolRouteImport } from './routes/_container/compare-tool'
import { Route as ContainerActivityRouteImport } from './routes/_container/activity'
import { Route as AtChar123nicknameChar125TradesRouteImport } from './routes/@{$nickname}/trades'
import { Route as AtChar123nicknameChar125StatsRouteImport } from './routes/@{$nickname}/stats'
import { Route as AtChar123nicknameChar125ProgressRouteImport } from './routes/@{$nickname}/progress'
import { Route as AtChar123nicknameChar125ListRouteImport } from './routes/@{$nickname}/list'
import { Route as ContainerLiveIndexRouteImport } from './routes/_container/live/index'
import { Route as ContainerListIndexRouteImport } from './routes/_container/list/index'
import { Route as ContainerLinkIndexRouteImport } from './routes/_container/link/index'
import { Route as ApiUserSearchRouteImport } from './routes/api/user.search'
import { Route as ApiTransfersAddressRouteImport } from './routes/api/transfers.$address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ContainerLiveIdRouteImport } from './routes/_container/live/$id'
import { Route as ContainerListSlugRouteImport } from './routes/_container/list/$slug'
import { Route as ContainerLinkConnectRouteImport } from './routes/_container/link/connect'
import { Route as ContainerAuthVerifiedRouteImport } from './routes/_container/auth/verified'
import { Route as ContainerAuthResetPasswordRouteImport } from './routes/_container/auth/reset-password'
import { Route as AtChar123nicknameChar125ListSlugRouteImport } from './routes/@{$nickname}/list.$slug'
import { Route as ApiObjektsOwnedByAddressRouteImport } from './routes/api/objekts/owned-by.$address'
import { Route as ApiObjektsMetadataCollectionSlugRouteImport } from './routes/api/objekts/metadata.$collectionSlug'
import { Route as ApiObjektsListCollectionSlugRouteImport } from './routes/api/objekts/list.$collectionSlug'
import { Route as ApiObjektsTransfersCollectionSlugSerialRouteImport } from './routes/api/objekts/transfers.$collectionSlug.$serial'

const ContainerRoute = ContainerRouteImport.update({
  id: '/_container',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123nicknameChar125RouteRoute =
  AtChar123nicknameChar125RouteRouteImport.update({
    id: '/@{$nickname}',
    path: '/@{$nickname}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContainerIndexRoute = ContainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContainerRoute,
} as any)
const AtChar123nicknameChar125IndexRoute =
  AtChar123nicknameChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenAppRoute = ApiOpenAppRouteImport.update({
  id: '/api/open-app',
  path: '/api/open-app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSessionsRoute = ApiLiveSessionsRouteImport.update({
  id: '/api/live-sessions',
  path: '/api/live-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckRoute = ApiHealthcheckRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollectionRoute = ApiCollectionRouteImport.update({
  id: '/api/collection',
  path: '/api/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivityRoute = ApiActivityRouteImport.update({
  id: '/api/activity',
  path: '/api/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerTermsPrivacyRoute = ContainerTermsPrivacyRouteImport.update({
  id: '/terms-privacy',
  path: '/terms-privacy',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLoginRoute = ContainerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerCompareToolRoute = ContainerCompareToolRouteImport.update({
  id: '/compare-tool',
  path: '/compare-tool',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerActivityRoute = ContainerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ContainerRoute,
} as any)
const AtChar123nicknameChar125TradesRoute =
  AtChar123nicknameChar125TradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const AtChar123nicknameChar125StatsRoute =
  AtChar123nicknameChar125StatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const AtChar123nicknameChar125ProgressRoute =
  AtChar123nicknameChar125ProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const AtChar123nicknameChar125ListRoute =
  AtChar123nicknameChar125ListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AtChar123nicknameChar125RouteRoute,
  } as any)
const ContainerLiveIndexRoute = ContainerLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerListIndexRoute = ContainerListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLinkIndexRoute = ContainerLinkIndexRouteImport.update({
  id: '/link/',
  path: '/link/',
  getParentRoute: () => ContainerRoute,
} as any)
const ApiUserSearchRoute = ApiUserSearchRouteImport.update({
  id: '/api/user/search',
  path: '/api/user/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransfersAddressRoute = ApiTransfersAddressRouteImport.update({
  id: '/api/transfers/$address',
  path: '/api/transfers/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerLiveIdRoute = ContainerLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerListSlugRoute = ContainerListSlugRouteImport.update({
  id: '/list/$slug',
  path: '/list/$slug',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerLinkConnectRoute = ContainerLinkConnectRouteImport.update({
  id: '/link/connect',
  path: '/link/connect',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerAuthVerifiedRoute = ContainerAuthVerifiedRouteImport.update({
  id: '/auth/verified',
  path: '/auth/verified',
  getParentRoute: () => ContainerRoute,
} as any)
const ContainerAuthResetPasswordRoute =
  ContainerAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => ContainerRoute,
  } as any)
const AtChar123nicknameChar125ListSlugRoute =
  AtChar123nicknameChar125ListSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AtChar123nicknameChar125ListRoute,
  } as any)
const ApiObjektsOwnedByAddressRoute =
  ApiObjektsOwnedByAddressRouteImport.update({
    id: '/api/objekts/owned-by/$address',
    path: '/api/objekts/owned-by/$address',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObjektsMetadataCollectionSlugRoute =
  ApiObjektsMetadataCollectionSlugRouteImport.update({
    id: '/api/objekts/metadata/$collectionSlug',
    path: '/api/objekts/metadata/$collectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObjektsListCollectionSlugRoute =
  ApiObjektsListCollectionSlugRouteImport.update({
    id: '/api/objekts/list/$collectionSlug',
    path: '/api/objekts/list/$collectionSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiObjektsTransfersCollectionSlugSerialRoute =
  ApiObjektsTransfersCollectionSlugSerialRouteImport.update({
    id: '/api/objekts/transfers/$collectionSlug/$serial',
    path: '/api/objekts/transfers/$collectionSlug/$serial',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/@{$nickname}': typeof AtChar123nicknameChar125RouteRouteWithChildren
  '/': typeof ContainerIndexRoute
  '/@{$nickname}/list': typeof AtChar123nicknameChar125ListRouteWithChildren
  '/@{$nickname}/progress': typeof AtChar123nicknameChar125ProgressRoute
  '/@{$nickname}/stats': typeof AtChar123nicknameChar125StatsRoute
  '/@{$nickname}/trades': typeof AtChar123nicknameChar125TradesRoute
  '/activity': typeof ContainerActivityRoute
  '/compare-tool': typeof ContainerCompareToolRoute
  '/login': typeof ContainerLoginRoute
  '/terms-privacy': typeof ContainerTermsPrivacyRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/collection': typeof ApiCollectionRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/live-sessions': typeof ApiLiveSessionsRoute
  '/api/open-app': typeof ApiOpenAppRoute
  '/rpc/$': typeof RpcSplatRoute
  '/@{$nickname}/': typeof AtChar123nicknameChar125IndexRoute
  '/@{$nickname}/list/$slug': typeof AtChar123nicknameChar125ListSlugRoute
  '/auth/reset-password': typeof ContainerAuthResetPasswordRoute
  '/auth/verified': typeof ContainerAuthVerifiedRoute
  '/link/connect': typeof ContainerLinkConnectRoute
  '/list/$slug': typeof ContainerListSlugRoute
  '/live/$id': typeof ContainerLiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/transfers/$address': typeof ApiTransfersAddressRoute
  '/api/user/search': typeof ApiUserSearchRoute
  '/link/': typeof ContainerLinkIndexRoute
  '/list/': typeof ContainerListIndexRoute
  '/live/': typeof ContainerLiveIndexRoute
  '/api/objekts/list/$collectionSlug': typeof ApiObjektsListCollectionSlugRoute
  '/api/objekts/metadata/$collectionSlug': typeof ApiObjektsMetadataCollectionSlugRoute
  '/api/objekts/owned-by/$address': typeof ApiObjektsOwnedByAddressRoute
  '/api/objekts/transfers/$collectionSlug/$serial': typeof ApiObjektsTransfersCollectionSlugSerialRoute
}
export interface FileRoutesByTo {
  '/@{$nickname}/list': typeof AtChar123nicknameChar125ListRouteWithChildren
  '/@{$nickname}/progress': typeof AtChar123nicknameChar125ProgressRoute
  '/@{$nickname}/stats': typeof AtChar123nicknameChar125StatsRoute
  '/@{$nickname}/trades': typeof AtChar123nicknameChar125TradesRoute
  '/activity': typeof ContainerActivityRoute
  '/compare-tool': typeof ContainerCompareToolRoute
  '/login': typeof ContainerLoginRoute
  '/terms-privacy': typeof ContainerTermsPrivacyRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/collection': typeof ApiCollectionRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/live-sessions': typeof ApiLiveSessionsRoute
  '/api/open-app': typeof ApiOpenAppRoute
  '/rpc/$': typeof RpcSplatRoute
  '/@{$nickname}': typeof AtChar123nicknameChar125IndexRoute
  '/': typeof ContainerIndexRoute
  '/@{$nickname}/list/$slug': typeof AtChar123nicknameChar125ListSlugRoute
  '/auth/reset-password': typeof ContainerAuthResetPasswordRoute
  '/auth/verified': typeof ContainerAuthVerifiedRoute
  '/link/connect': typeof ContainerLinkConnectRoute
  '/list/$slug': typeof ContainerListSlugRoute
  '/live/$id': typeof ContainerLiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/transfers/$address': typeof ApiTransfersAddressRoute
  '/api/user/search': typeof ApiUserSearchRoute
  '/link': typeof ContainerLinkIndexRoute
  '/list': typeof ContainerListIndexRoute
  '/live': typeof ContainerLiveIndexRoute
  '/api/objekts/list/$collectionSlug': typeof ApiObjektsListCollectionSlugRoute
  '/api/objekts/metadata/$collectionSlug': typeof ApiObjektsMetadataCollectionSlugRoute
  '/api/objekts/owned-by/$address': typeof ApiObjektsOwnedByAddressRoute
  '/api/objekts/transfers/$collectionSlug/$serial': typeof ApiObjektsTransfersCollectionSlugSerialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/@{$nickname}': typeof AtChar123nicknameChar125RouteRouteWithChildren
  '/_container': typeof ContainerRouteWithChildren
  '/@{$nickname}/list': typeof AtChar123nicknameChar125ListRouteWithChildren
  '/@{$nickname}/progress': typeof AtChar123nicknameChar125ProgressRoute
  '/@{$nickname}/stats': typeof AtChar123nicknameChar125StatsRoute
  '/@{$nickname}/trades': typeof AtChar123nicknameChar125TradesRoute
  '/_container/activity': typeof ContainerActivityRoute
  '/_container/compare-tool': typeof ContainerCompareToolRoute
  '/_container/login': typeof ContainerLoginRoute
  '/_container/terms-privacy': typeof ContainerTermsPrivacyRoute
  '/api/activity': typeof ApiActivityRoute
  '/api/collection': typeof ApiCollectionRoute
  '/api/healthcheck': typeof ApiHealthcheckRoute
  '/api/live-sessions': typeof ApiLiveSessionsRoute
  '/api/open-app': typeof ApiOpenAppRoute
  '/rpc/$': typeof RpcSplatRoute
  '/@{$nickname}/': typeof AtChar123nicknameChar125IndexRoute
  '/_container/': typeof ContainerIndexRoute
  '/@{$nickname}/list/$slug': typeof AtChar123nicknameChar125ListSlugRoute
  '/_container/auth/reset-password': typeof ContainerAuthResetPasswordRoute
  '/_container/auth/verified': typeof ContainerAuthVerifiedRoute
  '/_container/link/connect': typeof ContainerLinkConnectRoute
  '/_container/list/$slug': typeof ContainerListSlugRoute
  '/_container/live/$id': typeof ContainerLiveIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/transfers/$address': typeof ApiTransfersAddressRoute
  '/api/user/search': typeof ApiUserSearchRoute
  '/_container/link/': typeof ContainerLinkIndexRoute
  '/_container/list/': typeof ContainerListIndexRoute
  '/_container/live/': typeof ContainerLiveIndexRoute
  '/api/objekts/list/$collectionSlug': typeof ApiObjektsListCollectionSlugRoute
  '/api/objekts/metadata/$collectionSlug': typeof ApiObjektsMetadataCollectionSlugRoute
  '/api/objekts/owned-by/$address': typeof ApiObjektsOwnedByAddressRoute
  '/api/objekts/transfers/$collectionSlug/$serial': typeof ApiObjektsTransfersCollectionSlugSerialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/@{$nickname}'
    | '/'
    | '/@{$nickname}/list'
    | '/@{$nickname}/progress'
    | '/@{$nickname}/stats'
    | '/@{$nickname}/trades'
    | '/activity'
    | '/compare-tool'
    | '/login'
    | '/terms-privacy'
    | '/api/activity'
    | '/api/collection'
    | '/api/healthcheck'
    | '/api/live-sessions'
    | '/api/open-app'
    | '/rpc/$'
    | '/@{$nickname}/'
    | '/@{$nickname}/list/$slug'
    | '/auth/reset-password'
    | '/auth/verified'
    | '/link/connect'
    | '/list/$slug'
    | '/live/$id'
    | '/api/auth/$'
    | '/api/transfers/$address'
    | '/api/user/search'
    | '/link/'
    | '/list/'
    | '/live/'
    | '/api/objekts/list/$collectionSlug'
    | '/api/objekts/metadata/$collectionSlug'
    | '/api/objekts/owned-by/$address'
    | '/api/objekts/transfers/$collectionSlug/$serial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/@{$nickname}/list'
    | '/@{$nickname}/progress'
    | '/@{$nickname}/stats'
    | '/@{$nickname}/trades'
    | '/activity'
    | '/compare-tool'
    | '/login'
    | '/terms-privacy'
    | '/api/activity'
    | '/api/collection'
    | '/api/healthcheck'
    | '/api/live-sessions'
    | '/api/open-app'
    | '/rpc/$'
    | '/@{$nickname}'
    | '/'
    | '/@{$nickname}/list/$slug'
    | '/auth/reset-password'
    | '/auth/verified'
    | '/link/connect'
    | '/list/$slug'
    | '/live/$id'
    | '/api/auth/$'
    | '/api/transfers/$address'
    | '/api/user/search'
    | '/link'
    | '/list'
    | '/live'
    | '/api/objekts/list/$collectionSlug'
    | '/api/objekts/metadata/$collectionSlug'
    | '/api/objekts/owned-by/$address'
    | '/api/objekts/transfers/$collectionSlug/$serial'
  id:
    | '__root__'
    | '/@{$nickname}'
    | '/_container'
    | '/@{$nickname}/list'
    | '/@{$nickname}/progress'
    | '/@{$nickname}/stats'
    | '/@{$nickname}/trades'
    | '/_container/activity'
    | '/_container/compare-tool'
    | '/_container/login'
    | '/_container/terms-privacy'
    | '/api/activity'
    | '/api/collection'
    | '/api/healthcheck'
    | '/api/live-sessions'
    | '/api/open-app'
    | '/rpc/$'
    | '/@{$nickname}/'
    | '/_container/'
    | '/@{$nickname}/list/$slug'
    | '/_container/auth/reset-password'
    | '/_container/auth/verified'
    | '/_container/link/connect'
    | '/_container/list/$slug'
    | '/_container/live/$id'
    | '/api/auth/$'
    | '/api/transfers/$address'
    | '/api/user/search'
    | '/_container/link/'
    | '/_container/list/'
    | '/_container/live/'
    | '/api/objekts/list/$collectionSlug'
    | '/api/objekts/metadata/$collectionSlug'
    | '/api/objekts/owned-by/$address'
    | '/api/objekts/transfers/$collectionSlug/$serial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AtChar123nicknameChar125RouteRoute: typeof AtChar123nicknameChar125RouteRouteWithChildren
  ContainerRoute: typeof ContainerRouteWithChildren
  ApiActivityRoute: typeof ApiActivityRoute
  ApiCollectionRoute: typeof ApiCollectionRoute
  ApiHealthcheckRoute: typeof ApiHealthcheckRoute
  ApiLiveSessionsRoute: typeof ApiLiveSessionsRoute
  ApiOpenAppRoute: typeof ApiOpenAppRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTransfersAddressRoute: typeof ApiTransfersAddressRoute
  ApiUserSearchRoute: typeof ApiUserSearchRoute
  ApiObjektsListCollectionSlugRoute: typeof ApiObjektsListCollectionSlugRoute
  ApiObjektsMetadataCollectionSlugRoute: typeof ApiObjektsMetadataCollectionSlugRoute
  ApiObjektsOwnedByAddressRoute: typeof ApiObjektsOwnedByAddressRoute
  ApiObjektsTransfersCollectionSlugSerialRoute: typeof ApiObjektsTransfersCollectionSlugSerialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_container': {
      id: '/_container'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ContainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$nickname}': {
      id: '/@{$nickname}'
      path: '/@{$nickname}'
      fullPath: '/@{$nickname}'
      preLoaderRoute: typeof AtChar123nicknameChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_container/': {
      id: '/_container/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ContainerIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/@{$nickname}/': {
      id: '/@{$nickname}/'
      path: '/'
      fullPath: '/@{$nickname}/'
      preLoaderRoute: typeof AtChar123nicknameChar125IndexRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/open-app': {
      id: '/api/open-app'
      path: '/api/open-app'
      fullPath: '/api/open-app'
      preLoaderRoute: typeof ApiOpenAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-sessions': {
      id: '/api/live-sessions'
      path: '/api/live-sessions'
      fullPath: '/api/live-sessions'
      preLoaderRoute: typeof ApiLiveSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collection': {
      id: '/api/collection'
      path: '/api/collection'
      fullPath: '/api/collection'
      preLoaderRoute: typeof ApiCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activity': {
      id: '/api/activity'
      path: '/api/activity'
      fullPath: '/api/activity'
      preLoaderRoute: typeof ApiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_container/terms-privacy': {
      id: '/_container/terms-privacy'
      path: '/terms-privacy'
      fullPath: '/terms-privacy'
      preLoaderRoute: typeof ContainerTermsPrivacyRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/login': {
      id: '/_container/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ContainerLoginRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/compare-tool': {
      id: '/_container/compare-tool'
      path: '/compare-tool'
      fullPath: '/compare-tool'
      preLoaderRoute: typeof ContainerCompareToolRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/activity': {
      id: '/_container/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ContainerActivityRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/@{$nickname}/trades': {
      id: '/@{$nickname}/trades'
      path: '/trades'
      fullPath: '/@{$nickname}/trades'
      preLoaderRoute: typeof AtChar123nicknameChar125TradesRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/@{$nickname}/stats': {
      id: '/@{$nickname}/stats'
      path: '/stats'
      fullPath: '/@{$nickname}/stats'
      preLoaderRoute: typeof AtChar123nicknameChar125StatsRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/@{$nickname}/progress': {
      id: '/@{$nickname}/progress'
      path: '/progress'
      fullPath: '/@{$nickname}/progress'
      preLoaderRoute: typeof AtChar123nicknameChar125ProgressRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/@{$nickname}/list': {
      id: '/@{$nickname}/list'
      path: '/list'
      fullPath: '/@{$nickname}/list'
      preLoaderRoute: typeof AtChar123nicknameChar125ListRouteImport
      parentRoute: typeof AtChar123nicknameChar125RouteRoute
    }
    '/_container/live/': {
      id: '/_container/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof ContainerLiveIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/list/': {
      id: '/_container/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof ContainerListIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/link/': {
      id: '/_container/link/'
      path: '/link'
      fullPath: '/link/'
      preLoaderRoute: typeof ContainerLinkIndexRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/api/user/search': {
      id: '/api/user/search'
      path: '/api/user/search'
      fullPath: '/api/user/search'
      preLoaderRoute: typeof ApiUserSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transfers/$address': {
      id: '/api/transfers/$address'
      path: '/api/transfers/$address'
      fullPath: '/api/transfers/$address'
      preLoaderRoute: typeof ApiTransfersAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_container/live/$id': {
      id: '/_container/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof ContainerLiveIdRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/list/$slug': {
      id: '/_container/list/$slug'
      path: '/list/$slug'
      fullPath: '/list/$slug'
      preLoaderRoute: typeof ContainerListSlugRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/link/connect': {
      id: '/_container/link/connect'
      path: '/link/connect'
      fullPath: '/link/connect'
      preLoaderRoute: typeof ContainerLinkConnectRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/auth/verified': {
      id: '/_container/auth/verified'
      path: '/auth/verified'
      fullPath: '/auth/verified'
      preLoaderRoute: typeof ContainerAuthVerifiedRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/_container/auth/reset-password': {
      id: '/_container/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof ContainerAuthResetPasswordRouteImport
      parentRoute: typeof ContainerRoute
    }
    '/@{$nickname}/list/$slug': {
      id: '/@{$nickname}/list/$slug'
      path: '/$slug'
      fullPath: '/@{$nickname}/list/$slug'
      preLoaderRoute: typeof AtChar123nicknameChar125ListSlugRouteImport
      parentRoute: typeof AtChar123nicknameChar125ListRoute
    }
    '/api/objekts/owned-by/$address': {
      id: '/api/objekts/owned-by/$address'
      path: '/api/objekts/owned-by/$address'
      fullPath: '/api/objekts/owned-by/$address'
      preLoaderRoute: typeof ApiObjektsOwnedByAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objekts/metadata/$collectionSlug': {
      id: '/api/objekts/metadata/$collectionSlug'
      path: '/api/objekts/metadata/$collectionSlug'
      fullPath: '/api/objekts/metadata/$collectionSlug'
      preLoaderRoute: typeof ApiObjektsMetadataCollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objekts/list/$collectionSlug': {
      id: '/api/objekts/list/$collectionSlug'
      path: '/api/objekts/list/$collectionSlug'
      fullPath: '/api/objekts/list/$collectionSlug'
      preLoaderRoute: typeof ApiObjektsListCollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/objekts/transfers/$collectionSlug/$serial': {
      id: '/api/objekts/transfers/$collectionSlug/$serial'
      path: '/api/objekts/transfers/$collectionSlug/$serial'
      fullPath: '/api/objekts/transfers/$collectionSlug/$serial'
      preLoaderRoute: typeof ApiObjektsTransfersCollectionSlugSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AtChar123nicknameChar125ListRouteChildren {
  AtChar123nicknameChar125ListSlugRoute: typeof AtChar123nicknameChar125ListSlugRoute
}

const AtChar123nicknameChar125ListRouteChildren: AtChar123nicknameChar125ListRouteChildren =
  {
    AtChar123nicknameChar125ListSlugRoute:
      AtChar123nicknameChar125ListSlugRoute,
  }

const AtChar123nicknameChar125ListRouteWithChildren =
  AtChar123nicknameChar125ListRoute._addFileChildren(
    AtChar123nicknameChar125ListRouteChildren,
  )

interface AtChar123nicknameChar125RouteRouteChildren {
  AtChar123nicknameChar125ListRoute: typeof AtChar123nicknameChar125ListRouteWithChildren
  AtChar123nicknameChar125ProgressRoute: typeof AtChar123nicknameChar125ProgressRoute
  AtChar123nicknameChar125StatsRoute: typeof AtChar123nicknameChar125StatsRoute
  AtChar123nicknameChar125TradesRoute: typeof AtChar123nicknameChar125TradesRoute
  AtChar123nicknameChar125IndexRoute: typeof AtChar123nicknameChar125IndexRoute
}

const AtChar123nicknameChar125RouteRouteChildren: AtChar123nicknameChar125RouteRouteChildren =
  {
    AtChar123nicknameChar125ListRoute:
      AtChar123nicknameChar125ListRouteWithChildren,
    AtChar123nicknameChar125ProgressRoute:
      AtChar123nicknameChar125ProgressRoute,
    AtChar123nicknameChar125StatsRoute: AtChar123nicknameChar125StatsRoute,
    AtChar123nicknameChar125TradesRoute: AtChar123nicknameChar125TradesRoute,
    AtChar123nicknameChar125IndexRoute: AtChar123nicknameChar125IndexRoute,
  }

const AtChar123nicknameChar125RouteRouteWithChildren =
  AtChar123nicknameChar125RouteRoute._addFileChildren(
    AtChar123nicknameChar125RouteRouteChildren,
  )

interface ContainerRouteChildren {
  ContainerActivityRoute: typeof ContainerActivityRoute
  ContainerCompareToolRoute: typeof ContainerCompareToolRoute
  ContainerLoginRoute: typeof ContainerLoginRoute
  ContainerTermsPrivacyRoute: typeof ContainerTermsPrivacyRoute
  ContainerIndexRoute: typeof ContainerIndexRoute
  ContainerAuthResetPasswordRoute: typeof ContainerAuthResetPasswordRoute
  ContainerAuthVerifiedRoute: typeof ContainerAuthVerifiedRoute
  ContainerLinkConnectRoute: typeof ContainerLinkConnectRoute
  ContainerListSlugRoute: typeof ContainerListSlugRoute
  ContainerLiveIdRoute: typeof ContainerLiveIdRoute
  ContainerLinkIndexRoute: typeof ContainerLinkIndexRoute
  ContainerListIndexRoute: typeof ContainerListIndexRoute
  ContainerLiveIndexRoute: typeof ContainerLiveIndexRoute
}

const ContainerRouteChildren: ContainerRouteChildren = {
  ContainerActivityRoute: ContainerActivityRoute,
  ContainerCompareToolRoute: ContainerCompareToolRoute,
  ContainerLoginRoute: ContainerLoginRoute,
  ContainerTermsPrivacyRoute: ContainerTermsPrivacyRoute,
  ContainerIndexRoute: ContainerIndexRoute,
  ContainerAuthResetPasswordRoute: ContainerAuthResetPasswordRoute,
  ContainerAuthVerifiedRoute: ContainerAuthVerifiedRoute,
  ContainerLinkConnectRoute: ContainerLinkConnectRoute,
  ContainerListSlugRoute: ContainerListSlugRoute,
  ContainerLiveIdRoute: ContainerLiveIdRoute,
  ContainerLinkIndexRoute: ContainerLinkIndexRoute,
  ContainerListIndexRoute: ContainerListIndexRoute,
  ContainerLiveIndexRoute: ContainerLiveIndexRoute,
}

const ContainerRouteWithChildren = ContainerRoute._addFileChildren(
  ContainerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AtChar123nicknameChar125RouteRoute:
    AtChar123nicknameChar125RouteRouteWithChildren,
  ContainerRoute: ContainerRouteWithChildren,
  ApiActivityRoute: ApiActivityRoute,
  ApiCollectionRoute: ApiCollectionRoute,
  ApiHealthcheckRoute: ApiHealthcheckRoute,
  ApiLiveSessionsRoute: ApiLiveSessionsRoute,
  ApiOpenAppRoute: ApiOpenAppRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTransfersAddressRoute: ApiTransfersAddressRoute,
  ApiUserSearchRoute: ApiUserSearchRoute,
  ApiObjektsListCollectionSlugRoute: ApiObjektsListCollectionSlugRoute,
  ApiObjektsMetadataCollectionSlugRoute: ApiObjektsMetadataCollectionSlugRoute,
  ApiObjektsOwnedByAddressRoute: ApiObjektsOwnedByAddressRoute,
  ApiObjektsTransfersCollectionSlugSerialRoute:
    ApiObjektsTransfersCollectionSlugSerialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
